// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI370Bo88nVnTqU3OSz6UQRS_xOsCjlJI',
    appId: '1:964342072954:web:1cdd0a59f7be3d53a85dc3',
    messagingSenderId: '964342072954',
    projectId: 'movie-catalog-1618a',
    authDomain: 'movie-catalog-1618a.firebaseapp.com',
    storageBucket: 'movie-catalog-1618a.firebasestorage.app',
    measurementId: 'G-JRJ3S0CNQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdWr8xusQKAc0zf4UzwsAoHnAHwBVaFvY',
    appId: '1:964342072954:android:afd7c5a43dd18b78a85dc3',
    messagingSenderId: '964342072954',
    projectId: 'movie-catalog-1618a',
    storageBucket: 'movie-catalog-1618a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6vK5MBO-6XpZLSfAWBERLrmM70KdBHs4',
    appId: '1:964342072954:ios:bde69f9937fcb9cda85dc3',
    messagingSenderId: '964342072954',
    projectId: 'movie-catalog-1618a',
    storageBucket: 'movie-catalog-1618a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6vK5MBO-6XpZLSfAWBERLrmM70KdBHs4',
    appId: '1:964342072954:ios:bde69f9937fcb9cda85dc3',
    messagingSenderId: '964342072954',
    projectId: 'movie-catalog-1618a',
    storageBucket: 'movie-catalog-1618a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI370Bo88nVnTqU3OSz6UQRS_xOsCjlJI',
    appId: '1:964342072954:web:cae128b46c9bf547a85dc3',
    messagingSenderId: '964342072954',
    projectId: 'movie-catalog-1618a',
    authDomain: 'movie-catalog-1618a.firebaseapp.com',
    storageBucket: 'movie-catalog-1618a.firebasestorage.app',
    measurementId: 'G-PSE8EQNLK5',
  );
}
